### ISSUE TITLE
Menu control style not saving.

### ISSUE THREAD

**Issue by ShroomKing** [pathway27/bookr-mod-vita#7]
I'm used to using the circle button as the confirm button, however when setting "Menu control style: Asian" and exiting the app it resets to the "Western" setting, meaning i have to set it to "Asian" every time i start the app if i want to use circle as confirm.

Also something else i noticed when using the app was that sometimes, very rarely when switching between pages all the pages start showing up as blank(just white) until you restart the app. This seems to be random though and i have no idea why that could be.

Those are the only "issues" i was able to find, cheers.

**Comment by pathway27** [comment]
Hmm, yeah that's annoying. I've fixed it the new release, see how you go with it.
I've also bumped the heap memory which i'm hoping will get rid of that blank page issue.

Could you tell me the file type and size of the e-book your reading?

**Comment by ShroomKing** [comment]
oh wow for some reason i forgot to reply, so sorry about that.

so far i've only used it for reference manuals in PDF format. The smallest book in size was about 4mb with 15 pages, the biggest one is ~40mb with 200+ pages.  The blank page issue still happens in all of them.

**Comment by pathway27** [comment]
See the [latest release](https://github.com/pathway27/bookr-mod-vita/releases/tag/v0.4.0a) and try again. Feel free to re-open this with any issues.
